############# User configuration #############

substitutions:
  # nodemcuv2 board
  board: nodemcuv2
  sub_name: kitchen
  pin_gang_1: D0 #GPIO16
  pin_gang_2: D5 #GPIO14
  pin_gang_3: D1 #GPIO5

  pin_receiver_data: D2 #GPIO4
  determine_change_state: 50ms

  # pin_led_blue: D4
  
  # Wifi credentials
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ip_address: !secret ip_address
  ap_ssid: "vHomeSwitch"
  ap_password: "1234567890"

  # OTA and API
  ota_password: "esphome"
  api_password: "esphome"

########### End user configuration ###########

esphome:
  name: vhomeswitch
  platform: ESP8266
  board: $board

wifi:
  ssid: $wifi_ssid
  password: $wifi_password
  # use_address: $ip_address
  fast_connect: on
  ap:
    ssid: $ap_ssid
    password: $ap_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

binary_sensor:
  - platform: status
    name: "RF Switch Status"

  - platform: gpio
    name: "Gang1"
    id: change_gang_1
    pin:
      number: $pin_gang_1
      mode: INPUT_PULLUP
      inverted: False
    # filters:
    #   delayed_off: $determine_change_state
    on_press:
      then:
        - switch.turn_on: line_1
    on_release:
      then:
        - switch.turn_off: line_1

  - platform: gpio
    name: "Gang2"
    id: change_gang_2
    pin:
      number: $pin_gang_2
      mode: INPUT_PULLUP
      inverted: False
    # filters:
    #   delayed_off: $determine_change_state
    on_press:
      then:
        - switch.turn_on: line_2 
    on_release:
      then:
        - switch.turn_off: line_2

  - platform: gpio
    name: "Gang3"
    id: change_gang_3
    pin:
      number: $pin_gang_3
      mode: INPUT_PULLUP
      inverted: False
    # filters:
    #   delayed_off: $determine_change_state
    on_press:
      then:
        - switch.turn_on: line_3
    on_release:
      then:
        - switch.turn_off: line_3

remote_transmitter:
  pin: $pin_receiver_data
  carrier_duty_percent: 100%

switch:

  - platform: template
    name: "Line 1"
    id: line_1
    lambda: |-
      if (id(change_gang_1).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - logger.log: "Line 1 is ON"
      - remote_transmitter.transmit_rc_switch_raw:
          code: '000001000001010001010001'
          protocol: 1
          repeat: 
            times: 1
    turn_off_action:
      - logger.log: "Line 1 is OFF"
      - remote_transmitter.transmit_rc_switch_raw:
          code: '000001000001010001010001'
          protocol: 1
          repeat: 
            times: 1
    
  - platform: template
    name: "Line 2"
    id: line_2
    lambda: |-
      if (id(change_gang_2).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - logger.log: "Line 2 is ON"
      - remote_transmitter.transmit_rc_switch_raw:
          code: '000001000001010001010100'
          protocol: 1
          repeat: 
            times: 1
    turn_off_action:
      - logger.log: "Line 2 is OFF"
      - remote_transmitter.transmit_rc_switch_raw:
          code: '000001000001010001010100'
          protocol: 1
          repeat: 
            times: 1

  - platform: template
    name: "Line 3"
    id: line_3
    lambda: |-
      if (id(change_gang_3).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - logger.log: "Line 3 is ON"
      - remote_transmitter.transmit_rc_switch_raw:
          code: '000001000001010001111100'
          protocol: 1
          repeat: 
            times: 1
    turn_off_action:
      - logger.log: "Line 3 is OFF"
      - remote_transmitter.transmit_rc_switch_raw:
          code: '000001000001010001111100'
          protocol: 1
          repeat: 
            times: 1
